using InnoPV.Web.Models.CaseCompleteReport;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Net;
using System.Text.RegularExpressions;

namespace InnoPV.Web.Services.CaseCompleteReport.Pdf;

public class CaseCompletePdfDocument : IDocument
{
    private readonly CaseCompleteReportViewModel _model;

    public CaseCompletePdfDocument(CaseCompleteReportViewModel model)
    {
        _model = model;
    }

    public DocumentMetadata GetMetadata()
    {
        return DocumentMetadata.Default;
    }

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(25);

            page.DefaultTextStyle(x => x.FontSize(9));

            page.Header().Element(ComposeHeader);

            page.Content().PaddingTop(10).Element(ComposeContent);

            page.Footer().Element(ComposeFooter);
        });
    }

    private void ComposeHeader(IContainer container)
    {
        container
            .BorderBottom(1)
            .BorderColor(Colors.Blue.Darken2)
            .PaddingBottom(8)
            .Row(row =>
            {
                row.RelativeItem().Column(column =>
                {
                    column.Item()
                        .Text("InnoPV — Complete PV Case Report")
                        .FontSize(16)
                        .Bold()
                        .FontColor(Colors.Blue.Darken3);

                    column.Item()
                        .PaddingTop(3)
                        .Text($"Case No: {_model.CaseNo}")
                        .FontSize(10)
                        .FontColor(Colors.Grey.Darken2);
                });

                row.ConstantItem(160).Column(column =>
                {
                    column.Item()
                        .AlignRight()
                        .Element(StatusBadge);

                    column.Item()
                        .PaddingTop(5)
                        .AlignRight()
                        .Text(_model.IsSerious ? "Serious Case" : "Non-serious Case")
                        .FontSize(9)
                        .Bold()
                        .FontColor(_model.IsSerious ? Colors.Red.Darken2 : Colors.Green.Darken2);
                });
            });
    }

    private void StatusBadge(IContainer container)
    {
        container
            .Background(Colors.Blue.Medium)
            .PaddingHorizontal(8)
            .PaddingVertical(4)
            .Text(_model.Status.ToString())
            .FontSize(9)
            .Bold()
            .FontColor(Colors.White);
    }

    private void ComposeFooter(IContainer container)
    {
        container
            .BorderTop(1)
            .BorderColor(Colors.Grey.Lighten2)
            .PaddingTop(5)
            .AlignCenter()
            .Text(text =>
            {
                text.Span("Generated by InnoPV | ").FontSize(8);
                text.Span(DateTime.Now.ToString("dd-MMM-yyyy HH:mm")).FontSize(8);
                text.Span(" | Page ").FontSize(8);
                text.CurrentPageNumber().FontSize(8);
                text.Span(" of ").FontSize(8);
                text.TotalPages().FontSize(8);
            });
    }

    private void ComposeContent(IContainer container)
    {
        container.Column(column =>
        {
            column.Spacing(10);

            column.Item().Element(ComposeCaseSummary);

            column.Item().Element(c => Section(c, "1. Patient Details", ComposePatient));
            column.Item().Element(c => Section(c, "2. Reporter Details", ComposeReporter));
            column.Item().Element(c => Section(c, "3. Adverse Event Details", ComposeAdverseEvent));
            column.Item().Element(c => Section(c, "4. Suspect Product Details", ComposeSuspectProduct));
            column.Item().Element(c => Section(c, "5. Concomitant Medications", ComposeConcomitantMedications));
            column.Item().Element(c => Section(c, "6. Lab Details", ComposeLabDetails));
            column.Item().Element(c => Section(c, "7. Narrative", ComposeNarrative));
        });
    }

    private void ComposeCaseSummary(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Blue.Lighten2)
            .Background(Colors.Blue.Lighten5)
            .Padding(8)
            .Column(column =>
            {
                column.Item()
                    .Text("Case Summary")
                    .FontSize(12)
                    .Bold()
                    .FontColor(Colors.Blue.Darken3);

                column.Item()
                    .PaddingTop(6)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        AddSummaryCell(table, "Case No", _model.CaseNo);
                        AddSummaryCell(table, "Source", _model.CaseSource);
                        AddSummaryCell(table, "Receipt Date", Dt(_model.ReceiptDate));
                        AddSummaryCell(table, "Due Date", Dt(_model.DueDate));

                        AddSummaryCell(table, "Validity", _model.IsValidCase ? "Valid" : "Invalid");
                        AddSummaryCell(table, "Seriousness", _model.IsSerious ? "Serious" : "Non-serious");
                        AddSummaryCell(table, "Product", _model.InitialProductName);
                        AddSummaryCell(table, "Event", _model.InitialEventTerm);
                        AddSummaryCell(table, "Initial Narrative", _model.InitialNarrative);
                    });
            });
    }

    private void Section(IContainer container, string title, Action<IContainer> content)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(0)
            .Column(column =>
            {
                column.Item()
                    .Background(Colors.Grey.Lighten3)
                    .PaddingHorizontal(8)
                    .PaddingVertical(6)
                    .Text(title)
                    .FontSize(11)
                    .Bold()
                    .FontColor(Colors.Blue.Darken3);

                column.Item()
                    .Padding(8)
                    .Element(content);
            });
    }

    private void ComposePatient(IContainer container)
    {
        container.Table(table =>
        {
            TwoColumnTable(table);

            AddRow(table, "Patient Identifier", _model.Patient.PatientIdentifier);
            AddRow(table, "Patient Initials", _model.Patient.PatientInitials);
            AddRow(table, "Date of Birth", Dt(_model.Patient.DateOfBirth));
            AddRow(table, "Age", Join(_model.Patient.Age?.ToString(), _model.Patient.AgeUnit));
            AddRow(table, "Gender", _model.Patient.Gender);
            AddRow(table, "Weight", _model.Patient.WeightKg.HasValue ? $"{_model.Patient.WeightKg} kg" : "-");
            AddRow(table, "Height", _model.Patient.HeightCm.HasValue ? $"{_model.Patient.HeightCm} cm" : "-");
            AddRow(table, "Pregnant", _model.Patient.IsPregnant ? "Yes" : "No");
            AddRow(table, "Pregnancy Remarks", _model.Patient.PregnancyRemarks);
            AddRow(table, "Relevant Medical History", _model.Patient.RelevantMedicalHistory);
            AddRow(table, "Allergy History", _model.Patient.AllergyHistory);
            AddRow(table, "Other Information", _model.Patient.OtherPatientInformation);
        });
    }

    private void ComposeReporter(IContainer container)
    {
        container.Table(table =>
        {
            TwoColumnTable(table);

            AddRow(table, "Reporter Name", _model.Reporter.ReporterName);
            AddRow(table, "Reporter Type", _model.Reporter.ReporterType);
            AddRow(table, "Qualification", _model.Reporter.Qualification);
            AddRow(table, "Organization", _model.Reporter.OrganizationName);
            AddRow(table, "Department", _model.Reporter.Department);
            AddRow(table, "Email", _model.Reporter.Email);
            AddRow(table, "Phone", _model.Reporter.Phone);
            AddRow(table, "Address", _model.Reporter.Address);
            AddRow(table, "City", _model.Reporter.City);
            AddRow(table, "State", _model.Reporter.State);
            AddRow(table, "Country", _model.Reporter.Country);
            AddRow(table, "Date of Report", Dt(_model.Reporter.DateOfReport));
            AddRow(table, "Consent for Follow-up", _model.Reporter.ConsentForFollowUp ? "Yes" : "No");
            AddRow(table, "Remarks", _model.Reporter.ReporterRemarks);
        });
    }

    private void ComposeAdverseEvent(IContainer container)
    {
        container.Table(table =>
        {
            TwoColumnTable(table);

            AddRow(table, "Event Term", _model.AdverseEvent.EventTerm);
            AddRow(table, "Event Start Date", Dt(_model.AdverseEvent.EventStartDate));
            AddRow(table, "Event End Date", Dt(_model.AdverseEvent.EventEndDate));
            AddRow(table, "Outcome", _model.AdverseEvent.Outcome);
            AddRow(table, "Serious", _model.AdverseEvent.IsSerious ? "Yes" : "No");
            AddRow(table, "Seriousness Criteria", _model.AdverseEvent.SeriousnessCriteria);
            AddRow(table, "Event Description", _model.AdverseEvent.EventDescription);
            AddRow(table, "Treatment Given", _model.AdverseEvent.TreatmentGiven);
            AddRow(table, "Remarks", _model.AdverseEvent.EventRemarks);
        });
    }

    private void ComposeSuspectProduct(IContainer container)
    {
        container.Table(table =>
        {
            TwoColumnTable(table);

            AddRow(table, "Product Name", _model.SuspectProduct.ProductName);
            AddRow(table, "Generic Name", _model.SuspectProduct.GenericName);
            AddRow(table, "Batch No", _model.SuspectProduct.BatchNo);

            // Agar aapne ExpiryDate ViewModel me add kiya hai, to ye line uncomment kar sakte ho:
            // AddRow(table, "Expiry Date", Dt(_model.SuspectProduct.ExpiryDate));

            AddRow(table, "Dose", Join(_model.SuspectProduct.Dose, _model.SuspectProduct.DoseUnit));
            AddRow(table, "Route", _model.SuspectProduct.Route);
            AddRow(table, "Frequency", _model.SuspectProduct.Frequency);
            AddRow(table, "Therapy Start Date", Dt(_model.SuspectProduct.TherapyStartDate));
            AddRow(table, "Therapy Stop Date", Dt(_model.SuspectProduct.TherapyStopDate));
            AddRow(table, "Indication", _model.SuspectProduct.Indication);
            AddRow(table, "Action Taken", _model.SuspectProduct.ActionTaken);
            AddRow(table, "Dechallenge", _model.SuspectProduct.Dechallenge);
            AddRow(table, "Rechallenge", _model.SuspectProduct.Rechallenge);
            AddRow(table, "Causality Assessment", _model.SuspectProduct.CausalityAssessment);
            AddRow(table, "Remarks", _model.SuspectProduct.ProductRemarks);
        });
    }

    private void ComposeConcomitantMedications(IContainer container)
    {
        if (!_model.ConcomitantMedications.Any())
        {
            EmptyText(container, "No concomitant medication records available.");
            return;
        }

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(1.5f);
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn(1.4f);
                columns.RelativeColumn(2);
            });

            HeaderCell(table, "Medication");
            HeaderCell(table, "Dose");
            HeaderCell(table, "Route");
            HeaderCell(table, "Frequency");
            HeaderCell(table, "Therapy Period");
            HeaderCell(table, "Indication / Remarks");

            foreach (var item in _model.ConcomitantMedications)
            {
                BodyCell(table, item.MedicationName);
                BodyCell(table, Join(item.Dose, item.DoseUnit));
                BodyCell(table, item.Route);
                BodyCell(table, item.Frequency);
                BodyCell(table, $"{Dt(item.TherapyStartDate)} to {Dt(item.TherapyStopDate)}");
                BodyCell(table, Join(item.Indication, item.Remarks));
            }
        });
    }

    private void ComposeLabDetails(IContainer container)
    {
        if (!_model.LabDetails.Any())
        {
            EmptyText(container, "No lab detail records available.");
            return;
        }

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(1.5f);
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn(1.2f);
                columns.RelativeColumn(2);
            });

            HeaderCell(table, "Test");
            HeaderCell(table, "Date");
            HeaderCell(table, "Result");
            HeaderCell(table, "Unit");
            HeaderCell(table, "Normal Range");
            HeaderCell(table, "Clinical Significance / Remarks");

            foreach (var item in _model.LabDetails)
            {
                BodyCell(table, item.TestName);
                BodyCell(table, Dt(item.TestDate));
                BodyCell(table, item.ResultValue);
                BodyCell(table, item.Unit);
                BodyCell(table, item.NormalRange);
                BodyCell(table, Join(item.ClinicalSignificance, item.Remarks));
            }
        });
    }

    private void ComposeNarrative(IContainer container)
    {
        var narrativeText = HtmlToText(_model.Narrative);

        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Background(Colors.Grey.Lighten5)
            .Padding(8)
            .Text(string.IsNullOrWhiteSpace(narrativeText) ? "Narrative not available." : narrativeText)
            .FontSize(9)
            .LineHeight(1.35f);
    }

    private static void EmptyText(IContainer container, string message)
    {
        container
            .Background(Colors.Grey.Lighten5)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8)
            .Text(message)
            .Italic()
            .FontColor(Colors.Grey.Darken2);
    }

    private static void TwoColumnTable(TableDescriptor table)
    {
        table.ColumnsDefinition(columns =>
        {
            columns.RelativeColumn(1.3f);
            columns.RelativeColumn(2.7f);
        });
    }

    private static void AddSummaryCell(TableDescriptor table, string label, string? value)
    {
        table.Cell()
            .Padding(3)
            .Text(label)
            .FontSize(8)
            .Bold()
            .FontColor(Colors.Grey.Darken2);

        table.Cell()
            .Padding(3)
            .Text(V(value))
            .FontSize(8);
    }

    private static void AddRow(TableDescriptor table, string label, string? value)
    {
        table.Cell()
            .Element(LabelCellStyle)
            .Text(label)
            .FontSize(8)
            .Bold();

        table.Cell()
            .Element(ValueCellStyle)
            .Text(V(value))
            .FontSize(8);
    }

    private static void HeaderCell(TableDescriptor table, string text)
    {
        table.Cell()
            .Element(HeaderCellStyle)
            .Text(text)
            .FontSize(8)
            .Bold()
            .FontColor(Colors.Blue.Darken3);
    }

    private static void BodyCell(TableDescriptor table, string? text)
    {
        table.Cell()
            .Element(ValueCellStyle)
            .Text(V(text))
            .FontSize(8);
    }

    private static IContainer LabelCellStyle(IContainer container)
    {
        return container
            .Background(Colors.Grey.Lighten4)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(5);
    }

    private static IContainer ValueCellStyle(IContainer container)
    {
        return container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(5);
    }

    private static IContainer HeaderCellStyle(IContainer container)
    {
        return container
            .Background(Colors.Blue.Lighten4)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(5);
    }

    private static string V(string? value)
    {
        return string.IsNullOrWhiteSpace(value) ? "-" : value;
    }

    private static string Dt(DateTime? date)
    {
        return date.HasValue ? date.Value.ToString("dd-MMM-yyyy") : "-";
    }

    private static string Dt(DateTime date)
    {
        return date.ToString("dd-MMM-yyyy");
    }

    private static string Join(params string?[] values)
    {
        var result = values
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x!.Trim())
            .ToList();

        return result.Any() ? string.Join(" ", result) : "-";
    }

    private static string HtmlToText(string? html)
    {
        if (string.IsNullOrWhiteSpace(html))
        {
            return string.Empty;
        }

        var text = html;

        text = Regex.Replace(text, "<br\\s*/?>", "\n", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, "</p>", "\n\n", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, "<p.*?>", "", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, "<li.*?>", "• ", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, "</li>", "\n", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, "</ul>", "\n", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, "</ol>", "\n", RegexOptions.IgnoreCase);
        text = Regex.Replace(text, "<.*?>", string.Empty);

        return WebUtility.HtmlDecode(text).Trim();
    }
}